#!/bin/bash

curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
java -cp antlr-4.7.1-complete.jar org.antlr.v4.Tool -package ninja.soroosh.hashem.lang.parser -no-listener language/src/main/java/ninja/soroosh/hashem/lang/parser/HashemLanguage.g4
